name: HelloWorldPlugin # the plugins name as it should appear in the plugin list /pl
version: 0.7.0 # the plugin's version
commands:
  adSpammer:
    description: Starts or stops message spamming
    usage: /<command> <start|stop> [message]
author: tigobi
main: org.tigobi.plugin.HelloWorldPlugin
api-version: 1.20