name: HelloWorldPlugin # the plugins name as it should appear in the plugin list /pl
version: 0.7.0 # the plugin's version
commands:
  messageStart:
  description: start
  usage: /<command>
author: tigobi
main: org.tigobi.plugin.HelloWorldPlugin
api-version: 1.20